language.Add ("sent_countermeasure", "Countermeasure")
language.Add ("sent_GuidedHeliMissile", "Guided Missile")
language.Add ("sent_GuidedJetMissile", "Missile")
language.Add ("sent_Helicopter_nonAdmin", "Helicopter")
language.Add ("sent_JetBomb", "Bomb")
language.Add ("sent_LaserGuidedMissile", "Guided Missile")
language.Add ("sent_NoTargetJetMissile", "Missile")
language.Add ("sent_NoTargetMissile", "Missile")
language.Add ("sent_SakariasHelicopter", "Helicopter")
language.Add ("sent_SakariasJet", "F35")
language.Add ("sent_SakariasJet_nonAdmin", "F35")
language.Add ("sent_SakariasJet_nonAdmin_rfl", "RFL")
language.Add ("sent_SakariasJet_rfl", "RFL")

killicon.Add("sent_countermeasure", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_guidedgelimissile", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_guidedjetmissile", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_helicopter_nonadmin", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_jetbomb", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_laserguidedmissile", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_notargetjetmissile", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_notargetmissile", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_sakariashelicopter", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_sakariasjet", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_sakariasjet_nonadmin", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_sakariasjet_nonadmin_rfl", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )
killicon.Add("sent_sakariasjet_rfl", "VGUI/airveh_killicon", Color( 255, 255, 255, 255 ) )